<?php

declare(strict_types=1);

namespace App\Service;

use Psr\Log\LoggerInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class GeminiClient
{
    private const MODEL = 'gemini-2.0-flash-exp';
    private const API_URL = 'https://generativelanguage.googleapis.com/v1/models/';
    private const MAX_RETRIES = 3;
    private const RETRY_DELAY_MS = 1000;

    public function __construct(
        private HttpClientInterface $httpClient,
        private string $googleApiKey,
        private LoggerInterface $logger,
    ) {}

    public function generateContent(string $prompt, int $maxOutputTokens = 4096): string
    {
        if (empty(trim($prompt))) {
            $this->logger->warning('Gemini API called with empty prompt');
            throw new \InvalidArgumentException('Prompt cannot be empty');
        }

        $url = self::API_URL . self::MODEL . ':generateContent?key=' . $this->googleApiKey;

        for ($attempt = 1; $attempt <= self::MAX_RETRIES; $attempt++) {
            try {
                $response = $this->httpClient->request('POST', $url, [
                    'json' => [
                        'contents' => [
                            [
                                'parts' => [
                                    ['text' => $prompt]
                                ]
                            ]
                        ],
                        'generationConfig' => [
                            'temperature' => 0.7,
                            'topK' => 40,
                            'topP' => 0.95,
                            'maxOutputTokens' => $maxOutputTokens,
                        ]
                    ],
                    'timeout' => 30,
                ]);

                $statusCode = $response->getStatusCode();
                
                if ($statusCode >= 500) {
                    throw new \RuntimeException("Gemini API returned server error: {$statusCode}");
                }

                $data = $response->toArray();

                // Check for API errors in response
                if (isset($data['error'])) {
                    $errorMsg = $data['error']['message'] ?? 'Unknown API error';
                    $this->logger->error('Gemini API error', [
                        'error' => $errorMsg,
                        'code' => $data['error']['code'] ?? null,
                        'attempt' => $attempt,
                    ]);
                    throw new \RuntimeException("Gemini API error: {$errorMsg}");
                }

                if (!isset($data['candidates']) || !is_array($data['candidates']) || count($data['candidates']) === 0) {
                    $this->logger->warning('Gemini API returned no candidates', ['response' => $data]);
                    throw new \RuntimeException('No content generated by Gemini API');
                }

                $content = $data['candidates'][0]['content']['parts'][0]['text'] ?? null;
                
                if ($content === null) {
                    $finishReason = $data['candidates'][0]['finishReason'] ?? 'unknown';
                    $this->logger->warning('Gemini API returned empty content', ['finishReason' => $finishReason]);
                    throw new \RuntimeException("Content generation failed: {$finishReason}");
                }

                return $content;

            } catch (\Throwable $e) {
                $this->logger->error('Gemini API request failed', [
                    'attempt' => $attempt,
                    'max_retries' => self::MAX_RETRIES,
                    'error' => $e->getMessage(),
                    'exception' => get_class($e),
                ]);

                if ($attempt === self::MAX_RETRIES) {
                    throw new \RuntimeException(
                        "Failed to generate content after " . self::MAX_RETRIES . " attempts: " . $e->getMessage(),
                        previous: $e
                    );
                }

                usleep(self::RETRY_DELAY_MS * 1000 * $attempt);
            }
        }

        throw new \RuntimeException('Unexpected error in Gemini client');
    }
}
